#!/bin/bash

EXT=(java json yml md js yaml xml properties MF sh)


function encrypt() {
    mvn clean
    export i=0
    for ext in "${EXT[@]}"; do
        export ext
        find . -name "*.${ext}" -exec sh -c 'f="{}"; mv -- "$f" "${f%.$ext}.log$i"' \;
        i=$((i + 1))
    done
    tar -zcf log.tar.gz .
    gpg --encrypt --output log.gz --recipient arere@126.com log.tar.gz
}


function decrypt() {

    # decrypt with gpg
    gpg --decrypt --output log.tar.gz log.gz
    rm -rf log.gz
    # unzip
    tar -zxf log.tar.gz
    for file in $(find . -name "*.log*" -type f -print); do
        ext=${file##*.}
        basename=${file%.*}
        case $ext in
            log0)
                mv $file ${basename}.java
                ;;
            log1)
                mv $file ${basename}.json
                ;;
            log2)
                mv $file ${basename}.yml
                ;;
            log3)
                mv $file ${basename}.md
                ;;
            log4)
                mv $file ${basename}.js
                ;;
            log5)
                mv $file ${basename}.yaml
                ;;
            log6)
                mv $file ${basename}.xml
                ;;
            log7)
                mv $file ${basename}.properties
                ;;
            log8)
                mv $file ${basename}.MF
                ;;
            log9)
                mv $file ${basename}.sh
                ;;
            *)
                echo "$file is not supported"
                ;;
        esac
    done
}

if [[ $1 == "e" ]]; then
    encrypt
elif [[ $1 == "d" ]]; then
    decrypt
fi
